# Requires user iodine on the system
name: openvpn
description: Provides OpenVPN connectivity
provides:
  - connectable_ip@([[:graph:]]*)
  - receiving_vpn_tunnel@([[:graph:]]*)
executable: tactic.rb
daemon: daemon.rb
