# Requires user iodine on the system
name: iodine
description: Provides IP over DNS tunnel using iodine
provides:
  - connectable_ip@([[:graph:]]*)
requires:
  - local_ips@Destination
  - iodined_password@Destination
  - iodined_port@Destination
executable: tactic.rb
daemon: daemon.rb
