# Tests are run N minutes past the hour
log_dir: logs
ptccp_dir: ptccp
tunnels:
  - name: iodine
    time: 0
    ip: 10.0.0.1
    port: 5000
    interface: eth0
  - name: OpenVPN
    time: 10
    ip: 10.1.1.1
    port: 5000
    interface: eth0
  - name: httptunnel
    time: 20
    ip: 10.1.1.1
    port: 5000
    interface: eth0
  - name: ipsec
    time: 30
    ip: 10.1.1.1
    port: 5000
    interface: eth0
  - name: tcpcrypt
    time: 40
    ip: 10.1.1.1
    port: 5000
    interface: eth0
  - name: sshtunnel
    time: 50
    ip: 10.1.1.1
    port: 5000
    interface: eth0
